twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    # Services
    globals:
        outingService: '@App\Service\OutingService'

when@test:
    twig:
        strict_variables: true
